name: CI/CD for NPM Package (Alpine)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: node:22-alpine # Using Alpine-based Node.js container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    container: node:22-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run prettier:fix

  publish:
    name: Publish to NPM
    needs: [test, prettier] # Runs only if tests and prettier pass
    runs-on: ubuntu-latest
    container: node:22-alpine
    #if: github.event_name == 'release' # Only runs on GitHub releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up NPM
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Build package (if needed)
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
